// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcrzzxcgfcepepabqjtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcnp6eGNnZmNlcGVwYWJxanRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzU2MjYsImV4cCI6MjA2MDQ1MTYyNn0.2q034KKi49nIeLa6w7ofO8ekkUqcDuko0TU-m3jGT70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);